markdown:       kramdown
highlighter:    rouge

title:          'Endre A Wik'
tagline:        'I was born for this'
description:    'Donâ€™t play their game, make them play yours'
url:            https://endreawik.com
baseurl:        /

remote_theme:   fongandrew/hydeout

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate



sidebar_home_link:  true
# site.sidebar_home_link: true